tendermint/farming

x/farming/keeper/staking.go

These event emits were accidentally removed during the merge from an early stage of the project.
---

fix: revert the events for stake and unstake message server

---

x/farming/client/cli/cli_test.go
x/farming/client/cli/flags.go
x/farming/client/cli/tx.go

by specifing `--all` flag, staking-coin-denoms can be omitted
---

fix: make staking-coin-denoms a positional argument

---

x/farming/keeper/keeper_test.go
x/farming/keeper/reward.go
x/farming/keeper/reward_test.go

fix: Fix comparison bug when allocating all balances of the farming pool

---

.github/.codecov.yml
.github/workflows/test.yml
x/farming/keeper/proposal_handler.go
x/farming/keeper/proposal_handler_test.go
x/farming/types/plan.go
x/farming/types/proposal.go

feat: fix update public plan proposal & disable codecov patch

---

x/farming/keeper/reward.go
x/farming/keeper/reward_test.go

Add tests to test if the #126 has resolved.
closes: #126 
- #128 
---

test: add tests for HistoricalRewards

---

.github/workflows/sims.yml

This issue is further improvements of #98
closes: #153
---

test: add import and export simulation

---

x/farming/keeper/plan.go
x/farming/keeper/proposal_handler.go
x/farming/keeper/proposal_handler_test.go
x/farming/spec/08_proposal.md

closes: #161 
* Handle an edge case where `FarmingPoolAddress` and `TerminationAddress` are equal
---

fix: terminate plan when deleting public plan proposal

---

x/farming/keeper/reward.go
x/farming/spec/06_events.md
x/farming/types/events.go

`Keeper.WithdrawRewards` is called in several places:
- `Keeper.Harvest`
- `Keeper.ProcessQueuedCoins`
- `Keeper.Unstake`
so instead of emitting `harvest` event in `Keeper.Harvest`,
emit `rewards_withdrawn` event in these places.
note that this new event will be emitted
multiple times for a farmer(for each staking coin denom
the farmer has).
closes: #164 
---

fix: emit `rewards_withdrawn` event

---

x/farming/keeper/proposal_handler.go
x/farming/keeper/proposal_handler_test.go
x/farming/simulation/proposals.go
x/farming/types/msgs.go
x/farming/types/msgs_test.go
x/farming/types/plan.go
x/farming/types/plan_test.go
x/farming/types/proposal.go
x/farming/types/proposal_test.go

fix: do not allow empty plan name

---

x/farming/keeper/genesis_test.go
x/farming/keeper/grpc_query_test.go
x/farming/keeper/invariants_test.go
x/farming/keeper/reward.go
x/farming/keeper/reward_test.go
x/farming/keeper/staking.go
x/farming/types/keys.go

See #192 for details
few more changes:
closes: #192
---

fix: change the initial epoch to 1

---

docs/How-To/cli/README.md

README edits, see comments 
I suggest that you use code fence tick marks for each command and then use plain text between
introduce each command and provide a transition before the output and resulting files
When showing a command, explain the command first by talking about what it does. Then show the command. Then show its output in a separate output block
closes part of  https://github.com/tendermint/farming/issues/172
see and apply the [Technical content style guidance](https://docs.google.com/document/d/1isLGDpPYfZI2la6sLryp0sDyP1kOju9sazgUo-9CAsM/edit?usp=sharing) for Farming
---

docs: Update README.md farming edits

---

docs/Tutorials/demo/budget_with_farming.md

changes for grammar and consistent audience "you"
see the [Technical content style guidance](https://docs.google.com/document/d/1isLGDpPYfZI2la6sLryp0sDyP1kOju9sazgUo-9CAsM/edit?usp=sharing) for Farming 
most of the changes here tightened up language, provide consistency, changed audience to "you" 
good job! I did not run the demo, so I verify only the language 
closes: #XXXX
- 
---

docs: edit budget_with_farming.md demo text

---

x/farming/keeper/invariants_test.go

I just found that I forgot to implement `TestPositiveTotalStakingsAmountInvariant`.
`TestPlanTerminationStatusInvariant` is also left as empty, but that invariant check is considered to be removed entirely.
See #217 for details.
#217
---

test: implement test for PositiveTotalStakingsAmountInvariant

---

x/farming/keeper/genesis.go
x/farming/keeper/genesis_test.go
x/farming/keeper/reward.go
x/farming/keeper/reward_test.go
x/farming/keeper/staking.go
x/farming/keeper/staking_test.go
x/farming/types/errors.go
x/farming/types/genesis_test.go
x/farming/types/plan_test.go

Resolve TODO comments, finish undone tasks.
---

fix: resolve TODO comments

---

app/params/amino.go
app/params/proto.go
x/farming/client/testutil/cli_test.go
x/farming/keeper/genesis.go
x/farming/keeper/proposal_handler.go
x/farming/keeper/proposal_handler_test.go

fix: add plan type validation for public plan proposal

---

x/farming/client/cli/tx.go
x/farming/spec/01_concepts.md

- https://github.com/tendermint/farming/pull/190
---

fix: add error for all flag with offline, update docs for TerminationAddress

---

README.md
x/farming/types/params.go
x/farming/types/plan.go

closes: #XXXX
- https://github.com/tendermint/farming/issues/220
---

fix: refactor RewardsReserveAcc to be derived by deriveAddress

---

CHANGELOG.md
docs/Tutorials/demo/budget_with_farming.md
go.mod
go.sum

bump budget to v1.0.0, update changelog, demo docs for release farming v1.0.0
---

build: bump budget to v1.0.0, update changelog, demo docs

---

x/farming/abci.go
x/farming/keeper/reward_test.go
x/farming/keeper/staking.go
x/farming/keeper/staking_test.go

This PR implements delayed deletion of past historical rewards.
Closes: #240
---

fix: defer the deletion of past historical rewards to the end-block

---

x/farming/module.go
x/farming/simulation/operations_test.go
x/farming/simulation/proposals_test.go
x/farming/types/codec.go
x/farming/types/msgs.go
x/farming/types/msgs_test.go

This will make x/farming compatible with ledger devices
---

fix: register types on legacy amino codec

---

x/farming/keeper/reward_test.go
x/farming/keeper/staking.go
x/farming/keeper/staking_test.go
x/farming/spec/02_state.md

`CurrentEpoch` should be continuous even if all farmers has unstaked their coins.
---

fix: preserve `CurrentEpoch` when all farmers has unstaked

---

x/farming/keeper/reward.go
x/farming/keeper/reward_test.go

This prevents panics when `AdvanceEpoch` is called together with `Unstake` within the same block.
- https://github.com/cosmosquad-labs/squad/issues/260
---

fix: skip zero total stakings when allocating rewards

---

Makefile
docs/How-To/cli/README.md
docs/Tutorials/demo/budget_with_farming.md
docs/Tutorials/demo/plans.md
x/farming/client/cli/tx.go
x/farming/handler.go
x/farming/keeper/keeper.go
x/farming/keeper/keeper_test.go
x/farming/keeper/msg_server.go
x/farming/keeper/plan_test.go
x/farming/keeper/proposal_handler.go
x/farming/module_test.go
x/farming/simulation/operations.go
x/farming/simulation/operations_test.go
x/farming/spec/04_messages.md
x/farming/spec/08_proposal.md
x/farming/types/errors.go

Disable creation of `RatioPlan`s by default.
It can be enabled by passing `enableRatioPlan=true` build flag, just like `MsgAdvanceEpoch`.
- https://github.com/tendermint/farming/pull/258#issuecomment-1076134828
---

refactor: disable ratio plans by default
