tendermint/farming

go.mod, go.sum
close: https://github.com/tendermint/farming/issues/7
=> Bump sdk version to v0.43.0-rc1

app/app.go, app/genesis.go, app/test_helpers.go, x/farming/keeper/grpc_query.go, x/farming/keeper/plan_test.go, x/farming/keeper/reward.go
close: #3 
- Add test_helpers.go
- Fix iterator of Rewards By farmer
- Fix app.go module dependency
=> Add test_helpers, Fix iterator of rewards

.github/workflow/lint.yml, .github/workflow/test.yml, .gitignore, Makefile, x/farming/handler_test.go, x/farming/types/params_test.go
=> Add github workflow

app/app.go, x/farming/keeper/genesis.go, x/farming/keeper/keeper.go, x/farming/keeper/msg_server.go, x/farming/keeper/plan_test.go, x/farming/keeper/reward.go, x/farming/keeper/staking.go, x/farming/spec/02_state.md, x/farming/types/expected_keepers.go, x/farming/types/keys.go, x/farming/types/reward.go, x/farming/types/staking.go
- add farming module account on genesis with expected keeper
- add `StakingByFarmer`, `StakingByStakingCoinDenom` indexing for stakings
- cherrypick some functions from https://github.com/tendermint/farming/pull/15
=> Add kv indexing and iterator functions for staking

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/PULL_REQUEST_TEMPLATE.md
closes: #33 
- [tendermint/liquidity](https://github.com/tendermint/liquidity/tree/develop/.github/ISSUE_TEMPLATE)
=> Add issue, pr templates

go.mod, go.sum
closes: #31 
- [sdk diff](https://github.com/cosmos/cosmos-sdk/compare/v0.43.0-rc1...v0.43.0-rc2)
---
=> Bump sdk version to v0.43.0-rc2

x/farming/keeper/keeper.go, x/farming/keeper/reward.go, x/farming/keeper/reward_test.go, x/farming/types/keys.go
=> feat: record last distributed time and total distributed reward coins

docs/How-To/client.md, x/farming/client/cli/cli_test.go, x/farming/client/cli/tx.go, x/farming/client/testutil/cli_helpers.go, x/farming/keeper/msg_server.go, x/farming/keeper/proposal_handler.go, x/farming/types/errors.go, x/farming/types/msgs.go, x/farming/types/msgs_test.go, x/farming/types/plan.go, x/farming/types/plan_test.go, x/farming/types/proposal.go
=> feat: add transaction command-line interface

x/farming/keeper/invariants.go, x/farming/keeper/invariants_test.go, x/farming/keeper/plan_test.go, x/farming/types/keys.go, x/farming/types/params.go
=> Add invariant checks for staking, rewards

x/farming/keeper/keeper.go, x/farming/keeper/staking.go, x/farming/types/params.go
=> Add temporary global rewards reserve pool account

x/farming/keeper/invariants.go, x/farming/keeper/reward.go, x/farming/keeper/reward_test.go
This PR temporarily fixes the issue in reward distribution.
Later we should consider change kv-store structure to match plans with rewards.
---
=> Fix reward distribution

docs/How-To/client.md, docs/How-To/plans.md
These docs `client.md` and `plans.md` are mostly worked on the other PR. However, it needs a review and an update in regards of contents making sure it is written in a developer friendly manner.
closes: #44
---
=> docs: write documentation for command-line interface

x/farming/keeper/plan.go, x/farming/keeper/reward.go, x/farming/types/events.go
=> feat: add more end-block events

app/app.go, go.mod, go.sum
=> Bump Cosmos-SDK to v0.43.0-rc3

x/farming/keeper/proposal_handler.go, x/farming/keeper/proposal_handler_test.go, x/farming/types/proposal.go
=> feat: add tests for public plan proposal

x/farming/keeper/plan.go, x/farming/keeper/plan_test.go, x/farming/types/plan.go
=> Add GlobalPlanId and Fix init value to 0 from 1 

x/farming/abci.go, x/farming/keeper/epoch_test.go
=> fix: use `epoch_days` param

go.mod, go.sum
=> bump cosmos-sdk to v0.43.0

docs/Tutorials/demo.md
=> docs: add tutorial for MVP demo

app/app.go, app/app_test.go, x/farming/module.go
=> fix: solve module, sdk issues

README.md, go.mod, go.sum
closes: #95 
- Cosmos SDK v0.44.0 [Release Notes](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.44.0) and [CHANGELOG.md](https://github.com/cosmos/cosmos-sdk/blob/release/v0.44.x/CHANGELOG.md
)
- Tendermint v0.34.12 [Release Notes](https://github.com/tendermint/tendermint/releases/tag/v0.34.12) and  [CHANGELOG.md](https://github.com/tendermint/tendermint/blob/v0.34.12/CHANGELOG.md#changelog)
---
=> build: bump sdk from v0.43.0 to v0.44.0

x/farming/keeper/plan.go, x/farming/spec/02_state.md, x/farming/types/keys.go
=> fix: remove deprecated PlansByFarmer index

x/farming/types/plan.go
=> fix: add exception logic to unpack for unregistered case

x/farming/keeper/reward.go
=> fix: increase epoch only once for each AllocateRewards

README.md, docs/How-To/cli/README.md, go.mod, go.sum
closes: #129 
- https://github.com/tendermint/budget/releases/tag/v0.1.0
---
=> feat: bump budget to v0.1.0 and fix broken link on readme

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/PULL_REQUEST_TEMPLATE.md, README.md
=> docs: add badges and update issue template

.github/workflows/linkchecker.yml, CONTRIBUTING.md, docs/Explanation/ADR/README.md, docs/Explanation/README.md, docs/How-To/api/README.md, docs/How-To/cli/README.md, docs/README.md, docs/Tutorials/demo/demo_2021_08_06.md
This PR adds markdown link checker workflow to check all Markdown files for broken links every 24 hours.
closes: #138 
---
=> feat: add markdown links checker workflow

app/app.go, app/app_test.go, go.mod, go.sum, x/farming/simulation/operations.go
=> fix: remove minter perm and add liquidity module

docs/README.md, docs/Reference/README.md, docs/Reference/proposals/01_proposal.md, docs/Reference/proposals/README.md
closes: #147 
- [Reference docs in cosmos-cash project](https://github.com/allinbits/cosmos-cash/blob/main/docs/Reference/architecture/README.md)
---
=> docs: add Reference docs structure and add first signal proposal

x/farming/keeper/grpc_query.go, x/farming/keeper/keeper_test.go, x/farming/keeper/staking.go, x/farming/keeper/staking_test.go, x/farming/spec/02_state.md
Also add some more tests and update spec docs.
Closes: #179
---
=> fix: withdraw rewards only when staked amount changes

x/farming/keeper/invariants.go, x/farming/keeper/invariants_test.go
=> fix: remove `PlanTerminationStatusInvariant`

x/farming/keeper/reward_test.go
=> test: add test cases for reward allocation of ratio plan

README.md, go.mod, go.sum
- https://github.com/cosmos/cosmos-sdk/compare/v0.44.3...v0.44.5
---
=> build: bump cosmos-sdk to v0.44.5 from v0.44.3

x/farming/keeper/plan.go, x/farming/keeper/plan_test.go, x/farming/keeper/reward.go, x/farming/spec/02_state.md, x/farming/types/msgs.go, x/farming/types/plan.go
This PR applies suggestions during the audit review.
---
=> fix: Apply audit suggestions

x/farming/client/cli/tx.go
This PR fixes `RemovePlan` cmd's usage.
---
=> fix: fix RemovePlan cmd usage

Makefile, app/params/weights.go, go.mod, go.sum, x/farming/keeper/genesis_test.go, x/farming/keeper/invariants.go, x/farming/keeper/reward.go, x/farming/keeper/staking.go, x/farming/simulation/genesis.go, x/farming/simulation/operations.go, x/farming/simulation/operations_test.go, x/farming/simulation/proposals.go, x/farming/simulation/proposals_test.go, x/farming/spec/01_concepts.md, x/farming/spec/05_end_block.md, x/farming/spec/06_events.md, x/farming/spec/07_params.md, x/farming/spec/08_proposal.md, x/farming/types/params.go
closes: #251 
- fix: use spendable coins not balance
- [fix: bech32 as byte, spec ordering](https://github.com/tendermint/farming/pull/252/commits/f5443c97640b0ab5483db7d2adf619495a923f58)
- [fix: avoid nil slice on farming module](https://github.com/tendermint/farming/pull/252/commits/3c02dda364185f40e68086708d1893c17c228a2c)
- bump budget to v1.1.0, fix simulation
---
=> fix: use spendable coins not balance, avoid nil slice, sim, budget

app/sim_test.go, go.mod, go.sum, x/farming/keeper/reward.go
This PR makes the range-loops deterministic to avoid app hash collision.
---
=> fix: avoid non-deterministic map iteration
